<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Projeto Slim Framework 3</title>

    <link rel="stylesheet" href="<?= PATH ?>/public/css/estilo.css"/>
</head>
<body>
    <header id="topo-um">
        <div class="container">
            <h1 class="logo-site">Logo Site</h1>

            <nav id="menu">
                <ul>
                    <li><a href="<?= PATH ?>" alt="home">Home</a></li>
                    <li><a href="<?= PATH ?>/sobre" alt="sobre">Sobre</a></li>
                    <li><a href="<?= PATH ?>/contato" alt="contato">Contato</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section>
        <div class="container">