<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= isset($title) ? $title : 'Área Administrativa' ?></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded navbar-static-top">
        <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<?= PATH ?>" alt="home">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<?= PATH ?>/admin/posts" alt="posts">Posts<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="<?= PATH ?>/admin/usuarios" alt="usuarios">Usuários<span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <form class="form-inline my-2 my-md-0" style="margin:0 290px;">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<?= PATH ?>/admin/logout">&raquo; Sair</a>
            </li>
          </ul>
        </div>
        </div>
    </nav>