<div class="container">

    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h2>Editar Post</h2>

            <?php if (isset($error)): ?>
                <div class="alert alert-danger"><?= $error ?></div>
            <?php endif; ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Formulário de edição de post
                </div>

                <div class="panel-body">
                    <form action="<?= PATH ?>/admin/posts/<?= $post->id ?>/edit" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="titulo">Titulo</label>
                            <input type="text" class="form-control" name="titulo" id="titulo" placeholder="titulo" value="<?= $post->titulo ?>">
                        </div>

                        <div class="form-group">
                            <label for="descricao">Descrição</label>
                            <textarea name="descricao" class="form-control" id="descricao" cols="30" rows="10" placeholder="Descrição"><?= $post->descricao ?></textarea>
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Atualizar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>